name: Build and output document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build document
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add make
          make
    
    - name: Move built document
      run: |
        mv paper.pdf ./doc
        mv supplement.pdf ./doc
    
    - name: Install doc dependencies
      run: |
        python -m pip install --user --upgrade -r doc/requirements.txt

    - name: Build the docs
      working-directory: doc
      run: |
        make
        
    - name: Move built HTML docs
      working-directory: doc
      run: |
        mv _build/html ../docs_output
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: docs_output
        path: docs_output/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: docs_output # optional
        # Destination path
        path: docs_output # optional

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS }} 
      with:
        build_dir: docs_output/
