name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: xu-cheng/texlive-action/full@v1

    - name: Build documents
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
